# Generated by Django 6.0.7 on 2026-07-17 04:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_anonymous_names(apps, schema_editor):
    """Convert legacy participant names into AnonymousName UUID values."""
    AnonymousName = apps.get_model("events", "AnonymousName")
    EventParticipant = apps.get_model("events", "EventParticipant")

    for participant in EventParticipant.objects.exclude(anonymous_name__isnull=True):
        anonymous_name, _ = AnonymousName.objects.get_or_create(
            display_name=participant.anonymous_name,
        )
        participant.anonymous_name = str(anonymous_name.pk)
        participant.save(update_fields=["anonymous_name"])


def restore_anonymous_names(apps, schema_editor):
    """Restore display-name strings when this migration is reversed."""
    AnonymousName = apps.get_model("events", "AnonymousName")
    EventParticipant = apps.get_model("events", "EventParticipant")

    for participant in EventParticipant.objects.exclude(anonymous_name__isnull=True):
        anonymous_name = AnonymousName.objects.get(pk=participant.anonymous_name)
        participant.anonymous_name = anonymous_name.display_name
        participant.save(update_fields=["anonymous_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousName",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Anonymous Name",
                "verbose_name_plural": "Anonymous Names",
                "db_table": "anonymous_names",
                "ordering": ["display_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="eventparticipant",
            options={"ordering": ["-joined_at"]},
        ),
        migrations.RemoveIndex(
            model_name="eventparticipant",
            name="event_parti_event_i_fd6b59_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventparticipant",
            name="event_parti_is_acti_e7c2dd_idx",
        ),
        migrations.AddField(
            model_name="event",
            name="anonymous_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Tracks the next anonymous name allocation."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="anonymous_seed",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Random starting index for anonymous name allocation.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_anonymous_chat"], name="events_is_anon_6438b4_idx"
            ),
        ),
        migrations.RunPython(
            migrate_anonymous_names,
            restore_anonymous_names,
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="anonymous_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participants",
                to="events.anonymousname",
            ),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(
                fields=["event", "is_active"], name="event_parti_event_i_b647f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(
                fields=["anonymous_name"], name="event_parti_anonymo_c8717f_idx"
            ),
        ),
    ]
