# Generated by Django 6.0.7 on 2026-07-17 13:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_anonymousname_alter_eventparticipant_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Text content of the message.", max_length=2000
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event where this message was sent.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="events.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="The participant who sent the message.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="events.eventparticipant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Message",
                "verbose_name_plural": "Event Messages",
                "db_table": "event_messages",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"], name="event_message_idx"
                    ),
                    models.Index(
                        fields=["participant"], name="participant_message_idx"
                    ),
                ],
            },
        ),
    ]
