# Generated by Django 6.0.7 on 2026-07-14 06:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PasswordResetToken",
            new_name="AccountSetupToken",
        ),
    ]
