# Generated by Django 6.0.7 on 2026-07-14 03:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reveal_completed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="started_private_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_private_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "private_chat_rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("evidence_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="chat.privatechatroom",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevealRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reveal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_reveal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reveal_requests",
                        to="chat.privatechatroom",
                    ),
                ),
            ],
            options={
                "db_table": "reveal_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="privatechatroom",
            index=models.Index(
                fields=["user_one"], name="private_cha_user_on_0e5fcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privatechatroom",
            index=models.Index(
                fields=["user_two"], name="private_cha_user_tw_b02147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privatechatroom",
            index=models.Index(fields=["status"], name="private_cha_status_595501_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["room"], name="reports_room_id_7a5611_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["reporter"], name="reports_reporte_5cbb43_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reported_user"], name="reports_reporte_225900_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="reports_status_e83c1d_idx"),
        ),
        migrations.AddIndex(
            model_name="revealrequest",
            index=models.Index(fields=["room"], name="reveal_requ_room_id_fbeb57_idx"),
        ),
        migrations.AddIndex(
            model_name="revealrequest",
            index=models.Index(
                fields=["requester"], name="reveal_requ_request_d6f18f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revealrequest",
            index=models.Index(
                fields=["receiver"], name="reveal_requ_receive_c2d2ed_idx"
            ),
        ),
    ]
