# Generated by Django 6.0.7 on 2026-07-14 03:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text")], default="text", max_length=20
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.privatechatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "private_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["room"], name="private_mes_room_id_de3230_idx"
                    ),
                    models.Index(
                        fields=["sender"], name="private_mes_sender__35141e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="private_mes_created_77c601_idx"
                    ),
                ],
            },
        ),
    ]
