# Generated by Django 6.0.7 on 2026-07-16 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_privatemessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="revealrequest",
            index=models.Index(
                fields=["room", "receiver", "status"],
                name="reveal_requ_room_id_6a6faa_idx",
            ),
        ),
    ]
