# Generated by Django 6.0.7 on 2026-07-16 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_revealrequest_reveal_requ_room_id_6a6faa_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam"),
                    ("harassment", "Harassment"),
                    ("abusive_language", "Abusive Language"),
                    ("inappropriate_content", "Inappropriate Content"),
                    ("fake_identity", "Fake Identity"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["room", "reporter", "status"], name="reports_room_id_5f958b_idx"
            ),
        ),
    ]
