"""
Predefined anonymous display names.

These names are used to populate the AnonymousName table
through the custom Django management command.
"""

ANONYMOUS_NAMES = [
    "Sassy Process",
    "Underpaid Class",
    "Vintage PHP2",
    "Vintage Programmer",
    "YAMLYoda",
    "Whispering Cookie",
    "404 Docker2",
    "Deprecated Wizard",
    "Corrupted Programmer",
    "Sassy Legend",
    "Smoked Programmer",
    "Async Macro",
    "Turbo Bro",
    "Hyperactive Schema",
    "Cyber Object",
    "Turbo PHP2",
    "Stealthy Terminal",
    "Vintage Database",
    "Turbo Docker2",
    "Sneaky Token",
    "Smart Function",
    "Ancient Buddy",
    "Screaming Index",
    "Cursed Nerd",
    "Blurry Token",
    "Blurry Console",
    "Sarcastic Golang2",
    "Sneaky Function",
    "Neon Kernel",
    "500 Bit",
    "Crashed Cursor",
    "Broken Android2",
    "Roasted Byte",
    "Spaghetti Ninja",
    "Frozen Algorithm",
    "Nerf Kernel",
    "Blessed Token",
    "Cracked Bootcamper",
    "Dumb Server",
    "Nerf Cluster",
    "Lagging Interpreter",
    "500 Kernel",
    "Smoked Schema",
    "Lazy Cluster",
    "Overclocked Token",
    "Brilliant Token",
    "Overclocked Pal",
    "Undefined Index",
    "Cracked Cursor",
    "Caffeinated API",
    "Underpaid Pipeline",
    "CacheMeOutside",
    "Sneaky Engineer",
    "Roasted Java",
    "Chaotic Cyborg",
    "Rocket Container",
    "Fried Server",
    "Frozen Freelancer",
    "Frosty Geek",
    "KubernetesKing",
    "Frosty Rust2",
    "Lazy Console",
    "Whispering Ruby2",
    "Cyber Hacker",
    "MergeConflictMike",
    "Giggling Legend",
    "Brilliant Bro",
    "Turbo Algorithm",
    "Rocket Hacker",
    "Pixelated Client",
    "Sassy Kotlin2",
    "Toxic Server",
    "Dumb Hacker",
    "Retro Python2",
    "CookieMonster2",
    "Recursive Kernel",
    "Deprecated Engineer",
    "Cursed Android2",
    "RootAccessRachel",
    "Caffeinated Intern",
    "404NotFound",
    "ItsNotABugItsAFeature",
    "404 Loop",
    "Glitchy Cluster",
    "404PageFound",
    "Wholesome PHP2",
    "Legendary Pipeline",
    "Stealthy Ninja",
    "Cursed Newbie",
    "Rusty Object",
    "Vintage Nerd",
    "Binary Session",
    "Buggy Thread",
    "Frosty Constant",
    "Lazy Index",
    "Quantum Macro",
    "Turbo Router",
    "CopyPasteCarl",
    "Deprecated Pipeline",
    "Vintage Ninja",
    "Pwned Node",
    "SleepDeprivedDev",
    "Roasted Ninja",
    "Infinite Daemon",
    "Glitchy Cache",
    "Lagging Bit",
    "Binary Java",
    "Hyperactive API",
    "Crispy Session",
    "Sarcastic Index",
    "Ancient Python2",
    "Silent Wizard",
    "Silent Object",
    "Chaotic Router",
    "Fried Cursor",
    "GitBlameGuy",
    "BlueScreenBoy",
    "Digital Function",
    "Buffed Freelancer",
    "Spaghetti Developer",
    "StackTraceStacy",
    "Salty PHP2",
    "Glitchy Newbie",
    "Legendary Cursor",
    "Giggling Token",
    "Cracked Variable",
    "Melting Interpreter",
    "Digital Container",
    "Cracked Macro",
    "Stealthy Hacker",
    "Overclocked Freelancer",
    "BandwidthBaron",
    "ThrottleThelma",
    "Whispering Bro",
    "Loud Hacker",
    "Rocket Programmer",
    "Lagging Session",
    "SyntaxError",
    "Pwned Plugin",
    "undefinedIsNotAFunction",
    "404 Swift2",
    "Stealthy Cluster",
    "Nerf Cyborg",
    "Rocket Scala2",
    "Pwned Console",
    "Salty Python2",
    "Leetspeak Golang2",
    "Spaghetti Token",
    "Digital Class",
    "NullPointer Hacker",
    "Infinite Interpreter",
    "Clueless Daemon",
    "Silent Function",
    "Sassy Newbie",
    "Chill Cache",
    "Clueless Interpreter",
    "Supersonic Developer",
    "Vintage Sysadmin",
    "Blurry PHP2",
    "Rocket Bug",
    "Cyber Constant",
    "Underpaid Schema",
    "Confused Script",
    "Recursive Terminal",
    "Corrupted Swift2",
    "Chill Interpreter",
    "Clueless Plugin",
    "Corrupted Proxy",
    "Glitchy Console",
    "Dumb Rust2",
    "Sleepy AI",
    "Cracked Geek",
    "Blessed Cache",
    "Retro Rust2",
    "Stealthy Node",
    "Baked Nerd",
    "Sarcastic Compiler",
    "SegFaultSam",
    "Bubbling Macro",
    "Buffed Docker2",
    "Retro Dude",
    "Frozen Android2",
    "Noodle Kernel",
    "Brilliant Nerd",
    "Crashed API",
    "Genius Script",
    "Crispy Newbie",
    "Crashed Intern",
    "Binary Ninja",
    "Chill Kernel",
    "404 Object",
    "Noodle Scala2",
    "Sneaky Bot",
    "Salty Class",
    "AdminPasswordAdmin",
    "Grumpy Interpreter",
    "Spaghetti Byte",
    "Glitchy Cookie",
    "Frosty Perl2",
    "Lagging Newbie",
    "Buggy Guru",
    "Leetspeak PHP2",
    "OfflineOllie",
    "Panicked Cluster",
    "Supersonic Constant",
    "Overclocked Newbie",
    "Overclocked Buddy",
    "Grumpy Firewall",
    "Ancient Bit",
    "Cursed Function",
    "Whispering Macro",
    "Overpowered Session",
    "Cracked Legend",
    "Retro Nerd",
    "Pwned Daemon",
    "404 Process",
    "Cracked Loop",
    "Cyber Schema",
    "Legendary Object",
    "Screaming AI",
    "Undefined Sysadmin",
    "Loud Query",
    "Rocket Script",
    "Undefined Client",
    "Buggy Bug",
    "Screaming API",
    "Sassy Container",
    "Crispy Firewall",
    "Fried Loop",
    "Cursed Server",
    "Broken Rust2",
    "Confused Dude",
    "Broken Client",
    "Overclocked Hacker",
    "Whispering Daemon",
    "Bubbling Terminal",
    "Blurry Server",
    "Blurry Process",
    "Brilliant Cookie",
    "Sleepy Geek",
    "Lagging Android2",
    "Turbo Ninja",
    "Melting PHP2",
    "Turbo Bootcamper",
    "Whispering Server",
    "Loud Sysadmin",
    "Vintage Coder",
    "StackOverflowKid",
    "BufferOverflowBen",
    "Sleepy Swift2",
    "Overengineered Cookie",
    "Grumpy AI",
    "NullPointer Scala2",
    "Lagging Firewall",
    "Hacked Nerd",
    "Confused Client",
    "Corrupted Legend",
    "Grumpy Legend",
    "Brilliant Wizard",
    "Grumpy Perl2",
    "Digital Cache",
    "Silent Robot",
    "Nerf Wizard",
    "Pwned Cyborg",
    "Sassy Dude",
    "Legendary Developer",
    "Leetspeak Nerd",
    "MemoryLeakMax",
    "Broken Engineer",
    "NullException",
    "Infinite Terminal",
    "Stealthy API",
    "Grumpy Developer",
    "NullPointer Byte",
    "Crispy Schema",
    "Binary Pal",
    "Ninja Variable",
    "Underpaid PHP2",
    "Bubbling Thread",
    "CompileTimeCrisis",
    "Frozen Bro",
    "Ancient Guru",
    "Quantum Variable",
    "Ninja Docker2",
    "Underpaid Container",
    "Brilliant Geek",
    "Genius Legend",
    "Roasted Thread",
    "Crispy Python2",
    "Undefined Kotlin2",
    "Turbocharged Developer",
    "WifiWarrior",
    "Nerf Hacker",
    "Broken Swift2",
    "Silent Programmer",
    "Brilliant Scala2",
    "Melting Function",
    "Bubbling Buddy",
    "Buffed Index",
    "Ninja Java",
    "Dumb Database",
    "Salty Coder",
    "Confused Sysadmin",
    "Dumb Firewall",
    "Rusty Firewall",
    "Pwned Coder",
    "Overclocked Intern",
    "LoopyLoopz",
    "Blessed Schema",
    "Wholesome Bug",
    "Cracked Interpreter",
    "Sarcastic Node",
    "LatencyLord",
    "Neon Buddy",
    "Frozen Daemon",
    "Roasted Freelancer",
    "Stealthy Freelancer",
    "CoffeeToCode",
    "Confused Plugin",
    "Buggy Golang2",
    "Cursed Router",
    "Cursed Array",
    "Chill Bot",
    "Digital Java",
    "Panicked Ruby2",
    "Cracked Golang2",
    "Broken Cluster",
    "Rusty Python2",
    "LastCommitBeforeCrash",
    "RuntimeRebel",
    "Smoked Container",
    "Dumb Legend",
    "Grumpy Pixel",
    "Buggy Developer",
    "Neon Script",
    "Frosty Variable",
    "DeadlineDynamo",
    "Underpaid Router",
    "Rocket Index",
    "Sassy Widget",
    "Quantum Developer",
    "Overclocked Array",
    "Deprecated Widget",
    "Lazy Token",
    "Toxic PHP2",
    "Binary Debugger",
    "Baked Java",
    "Buffed Loop",
    "NullPointerNinja",
    "Wholesome Android2",
    "Sneaky Bit",
    "404 Guru",
    "Loud Guru",
    "Neon Ruby2",
    "Ancient Java",
    "Undefined Scala2",
    "Giggling Bootcamper",
    "Baked Macro",
    "Underpaid Ruby2",
    "Noodle Plugin",
    "Frozen Database",
    "TabsVsSpaces",
    "Roasted Ruby2",
    "Neon Process",
    "Pwned Cursor",
    "Legendary Perl2",
    "Overclocked Session",
    "Stealthy Cursor",
    "ForceQuitFred",
    "TypeErrorTony",
    "Chill Database",
    "Noodle Algorithm",
    "Brilliant Swift2",
    "Frozen Sysadmin",
    "Broken Coder",
    "Neon Object",
    "Confused Python2",
    "Frosty Interpreter",
    "Lazy Nerd",
    "Digital Plugin",
    "Clueless API",
    "PingPongPacket",
    "Broken Newbie",
    "Vintage Dude",
    "Undefined Python2",
    "HTTPStatusHero",
    "PacketLossPaul",
    "Rusty Session",
    "ExceptionEddie",
    "Sleepy Coder",
    "404 Newbie",
    "Overpowered Database",
    "Retro Scala2",
    "Whispering Pal",
    "Clueless Compiler",
    "Crashed Loop",
    "Caffeinated Cyborg",
    "Turbocharged Array",
    "Sassy Ruby2",
    "Overengineered Container",
    "Sleepy Hacker",
    "Neon Pixel",
    "Turbo Cyborg",
    "Crashed Robot",
    "Glitchy Proxy",
    "500 Interpreter",
    "Frosty Client",
    "Clueless Function",
    "Stealthy Ruby2",
    "Fried Router",
    "Binary AI",
    "Crispy Geek",
    "TryCatchTina",
    "Clueless Cursor",
    "Spaghetti Sysadmin",
    "Async Kotlin2",
    "Frozen Debugger",
    "Neon Thread",
    "Fried Process",
    "Sassy Node",
    "Sneaky Pixel",
    "Stealthy Newbie",
    "Overclocked Nerd",
    "Undefined Buddy",
    "Silent Cluster",
    "Clueless Wizard",
    "Overengineered Newbie",
    "Grumpy Newbie",
    "Sassy Script",
    "Overengineered Class",
    "Sleepy Cluster",
    "Overclocked Perl2",
    "Chaotic Engineer",
    "Frozen Interpreter",
    "Lagging Python2",
    "Broken Legend",
    "Sarcastic API",
    "Rusty Guru",
    "Vintage Robot",
    "Infinite Process",
    "Cyber Node",
    "Infinite Docker2",
    "Chaotic API",
    "Neon Debugger",
    "InfiniteLooper",
    "404 Geek",
    "Lazy Firewall",
    "Async Developer",
    "Neon Function",
    "Glitchy Buddy",
    "Async Widget",
    "ZeroDayZeke",
    "Bubbling Hacker",
    "Fried Debugger",
    "Caffeinated Bit",
    "Brilliant Pipeline",
    "Genius AI",
    "Caffeinated Bootcamper",
    "Melting Docker2",
    "Sleepy Perl2",
    "Spaghetti Plugin",
    "CtrlAltDefeat",
    "CloudNineDev",
    "Brilliant Byte",
    "Chaotic Plugin",
    "FinallyFinn",
    "Roasted Database",
    "Digital Router",
    "Blurry Algorithm",
    "Rocket Node",
    "SemicolonMissing",
    "Baked Bootcamper",
    "Confused Byte",
    "Recursive Docker2",
    "Rusty Robot",
    "404 Android2",
    "Sarcastic Query",
    "Cyber Script",
    "Corrupted Terminal",
    "Melting Cyborg",
    "Supersonic Widget",
    "Baked Scala2",
    "Grumpy Constant",
    "Blurry Bot",
    "ProductionDown",
    "Supersonic Intern",
    "Async Proxy",
    "Fried Geek",
    "Silent Console",
    "Buggy Cursor",
    "Wholesome Query",
    "Wholesome Debugger",
    "DockerWhale",
    "500 Ninja",
    "Wholesome Intern",
    "JSONParseJoe",
    "AutoCompleteAndy",
    "Undefined Daemon",
    "Toxic AI",
    "Screaming Pipeline",
    "NullPointer Thread",
    "Giggling Console",
    "Clueless Hacker",
    "Vintage Bot",
    "Quantum Proxy",
    "Fried Cache",
    "Clueless Geek",
    "Digital Bro",
    "Sneaky Ruby2",
    "Clueless Token",
    "Broken Loop",
    "RecursionReggie",
    "Async Schema",
    "Sarcastic Function",
    "Panicked Legend",
    "Nerf Token",
    "Hyperactive Object",
    "Cyber Golang2",
    "Sneaky API",
    "Async Cookie",
    "Lagging Geek",
    "Vintage Server",
    "ArrayOutOfBounds",
    "Baked AI",
    "Screaming Server",
    "Baked Cookie",
    "Lazy Widget",
    "Overclocked Ninja",
    "Corrupted Schema",
    "Infinite Engineer",
    "Buggy Legend",
    "RegexRebel",
    "Bubbling Bootcamper",
    "Ninja Intern",
    "Blurry Java",
    "Leetspeak Cursor",
    "Smart Server",
    "Sassy Byte",
    "Brilliant Kernel",
    "Melting Thread",
    "Blurry Perl2",
    "Melting Daemon",
    "Recursive Index",
    "NullPointer Intern",
    "Toxic Client",
    "Crashed Ruby2",
    "Chaotic Debugger",
    "Infinite Cookie",
    "WorksOnMyMachine",
    "Pixelated Function",
]
